version: 3.0.1-build{build}
environment:
  VisualStudioVersion: 14.0
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 3.1.0
  assembly_file_version: 3.1.0.{build}
  assembly_informational_version: '3.1.0-build{build}'
build:
  project: Imgur.API.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: '**\*.tests.dll'
artifacts:
  path: artifacts\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/imgur-api/api/v2
  api_key:
    secure: VKpWEiDhfRypjFf7MgnSlOJBdzQ1sOT87+aUCzjpj0wAFE8pOLJxcbXPR/6qqVBU
  symbol_server: https://nuget.symbolsource.org/MyGet/imgur-api